module.exports = {
  port: process.env.PORT || 9050,
  pgUser: process.env.PGUSER || "postgres",
  pgHost: process.env.PGHOST || "localhost",
  pgDatabase: process.env.PGDATABASE || "FileUserDataBase",
  pgPassword: process.env.PGPASSWORD || "12345",
  pgPort: process.env.PGPORT || 5432,
  KEY: "pp",
  TIME: "1h",
FolderTomonitor: "",
 path: "/Users/apoorvasingh/Desktop",
 recycleBinPath: "/Users/apoorvasingh/Desktop",
timeUnit:'days',
 timeValue:3,
 HTTP_OK: 200,
HTTP_CREATED: 201,
HTTP_INTERNAL_SERVER_ERROR: 500,
HTTP_NOT_FOUND: 404,
HTTP_BAD_REQUEST: 400,
HTTP_UNAUTHORIZED: 401,
LOG_FILE_MAX_SIZE: "10m",
  LOG_FILE_DELETE_DAYS: "14",

};
